import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

const PLAN_ITEMS: Record<string, { description: string; price: number }> = {
  starter: { description: "HufManager Starter – Monatslizenz", price: 9.90 },
  pro: { description: "HufManager Pro – Monatslizenz", price: 29.00 },
  duo: { description: "HufManager Duo – Monatslizenz", price: 49.00 },
  team: { description: "HufManager Team – Monatslizenz", price: 79.00 },
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceKey);

    // Check if auto-invoicing is enabled (simple flag check)
    // For now, this function is manually triggered or via cron
    // Auto-generation is DISABLED by default

    const now = new Date();
    const periodStart = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().split("T")[0];
    const periodEnd = new Date(now.getFullYear(), now.getMonth() + 1, 0).toISOString().split("T")[0];
    const dueDate = new Date(now.getFullYear(), now.getMonth(), 15).toISOString().split("T")[0];

    // Get active contracts with bank_transfer payment
    const { data: contracts, error: contractErr } = await supabase
      .from("admin_contracts")
      .select("*")
      .eq("status", "active")
      .eq("payment_method", "bank_transfer");

    if (contractErr) throw contractErr;
    if (!contracts || contracts.length === 0) {
      return new Response(JSON.stringify({ message: "No bank_transfer contracts to invoice" }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const results: any[] = [];

    for (const contract of contracts) {
      // Check if invoice already exists for this period
      const { data: existing } = await supabase
        .from("admin_invoices")
        .select("id")
        .eq("provider_id", contract.provider_id)
        .gte("period_start", periodStart)
        .lte("period_end", periodEnd)
        .limit(1);

      if (existing && existing.length > 0) continue;

      const planItem = PLAN_ITEMS[contract.plan] || PLAN_ITEMS.starter;
      const price = contract.custom_price || planItem.price;

      // Get provider info
      const { data: profile } = await supabase
        .from("profiles")
        .select("full_name, email, readable_id")
        .eq("id", contract.provider_id)
        .maybeSingle();

      if (!profile) continue;

      // Create invoice
      const { data: invoice, error: invErr } = await supabase
        .from("admin_invoices")
        .insert({
          invoice_number: "", // Auto-generated by trigger
          provider_id: contract.provider_id,
          provider_pid: profile.readable_id || contract.provider_pid,
          provider_name: profile.full_name || "Unbekannt",
          provider_email: profile.email || "",
          plan: contract.plan,
          period_start: periodStart,
          period_end: periodEnd,
          subtotal: price,
          total: price,
          kleinunternehmer: true,
          payment_method: "bank_transfer",
          payment_source: "auto_cron",
          status: "draft",
          due_date: dueDate,
        })
        .select("id, invoice_number")
        .single();

      if (invErr) {
        console.error(`Error creating invoice for ${profile.full_name}:`, invErr);
        results.push({ provider: profile.full_name, error: invErr.message });
        continue;
      }

      // Create invoice item
      await supabase.from("admin_invoice_items").insert({
        invoice_id: invoice.id,
        position: 1,
        description: planItem.description,
        quantity: 1,
        unit: "Monat",
        unit_price: price,
        total: price,
      });

      results.push({
        provider: profile.full_name,
        invoice_number: invoice.invoice_number,
        amount: price,
      });
    }

    return new Response(JSON.stringify({ generated: results.length, results }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (error: any) {
    console.error("auto-generate-invoices error:", error);
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
