import { DocumentBlock } from "./types";

function uid(): string {
  return crypto.randomUUID();
}

export const PRESET_TEMPLATES: {
  name: string;
  description: string;
  category: string;
  blocks: DocumentBlock[];
}[] = [
  {
    name: "Hufbearbeitungsprotokoll",
    description: "Dokumentation einer Hufbearbeitung inkl. Befund und Maßnahmen",
    category: "protokoll",
    blocks: [
      { id: uid(), type: "heading", value: "Hufbearbeitungsprotokoll", headingLevel: 1 },
      { id: uid(), type: "separator" },
      { id: uid(), type: "placeholder", placeholderKey: "date", label: "Datum" },
      { id: uid(), type: "placeholder", placeholderKey: "horse_name", label: "Pferd" },
      { id: uid(), type: "placeholder", placeholderKey: "client_name", label: "Besitzer:in" },
      { id: uid(), type: "placeholder", placeholderKey: "provider_name", label: "Bearbeiter:in" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "heading", value: "Befund vor Bearbeitung", headingLevel: 2 },
      { id: uid(), type: "checklist", label: "Hufzustand", checklistItems: [
        { id: uid(), label: "Hufwand intakt", checked: false },
        { id: uid(), label: "Sohle gesund", checked: false },
        { id: uid(), label: "Strahl gesund", checked: false },
        { id: uid(), label: "Trachten gleichmäßig", checked: false },
        { id: uid(), label: "Hufmechanismus funktional", checked: false },
      ]},
      { id: uid(), type: "textarea", label: "Besonderheiten / Auffälligkeiten", placeholder: "Beschreibung des Ausgangszustands..." },
      { id: uid(), type: "heading", value: "Durchgeführte Maßnahmen", headingLevel: 2 },
      { id: uid(), type: "checklist", label: "Arbeitsschritte", checklistItems: [
        { id: uid(), label: "Ausschneiden", checked: false },
        { id: uid(), label: "Raspeln", checked: false },
        { id: uid(), label: "Sohle bearbeitet", checked: false },
        { id: uid(), label: "Strahl bearbeitet", checked: false },
        { id: uid(), label: "Hufschutz angebracht", checked: false },
      ]},
      { id: uid(), type: "textarea", label: "Zusätzliche Maßnahmen / Empfehlungen", placeholder: "Weitere Details..." },
      { id: uid(), type: "heading", value: "Gangbild nach Bearbeitung", headingLevel: 2 },
      { id: uid(), type: "dropdown", label: "Gangbild", options: [
        { label: "Unauffällig", value: "unauffaellig" },
        { label: "Leichte Unregelmäßigkeit", value: "leicht" },
        { label: "Deutliche Unregelmäßigkeit", value: "deutlich" },
        { label: "Nicht beurteilt", value: "nicht_beurteilt" },
      ]},
      { id: uid(), type: "image", label: "Foto nach Bearbeitung" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "heading", value: "Abnahme", headingLevel: 2 },
      { id: uid(), type: "signature", label: "Unterschrift Besitzer:in" },
      { id: uid(), type: "note", label: "Hinweis", value: "Hiermit bestätige ich die ordnungsgemäße Durchführung der Hufbearbeitung." },
    ],
  },
  {
    name: "Erstaufnahme Pferd",
    description: "Erstanamnese eines neuen Pferdes",
    category: "aufnahme",
    blocks: [
      { id: uid(), type: "heading", value: "Erstaufnahme – Pferdedaten", headingLevel: 1 },
      { id: uid(), type: "separator" },
      { id: uid(), type: "placeholder", placeholderKey: "date", label: "Datum" },
      { id: uid(), type: "input", label: "Name des Pferdes", placeholder: "z.B. Luna", required: true },
      { id: uid(), type: "input", label: "Rasse", placeholder: "z.B. Haflinger" },
      { id: uid(), type: "number", label: "Alter (Jahre)" },
      { id: uid(), type: "input", label: "Farbe" },
      { id: uid(), type: "dropdown", label: "Geschlecht", options: [
        { label: "Stute", value: "stute" },
        { label: "Wallach", value: "wallach" },
        { label: "Hengst", value: "hengst" },
      ]},
      { id: uid(), type: "separator" },
      { id: uid(), type: "heading", value: "Besitzer:in", headingLevel: 2 },
      { id: uid(), type: "placeholder", placeholderKey: "client_name", label: "Name" },
      { id: uid(), type: "input", label: "Telefon" },
      { id: uid(), type: "input", label: "Stallort / Adresse" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "heading", value: "Hufsituation", headingLevel: 2 },
      { id: uid(), type: "dropdown", label: "Aktueller Hufschutz", options: [
        { label: "Barhuf", value: "barhuf" },
        { label: "Eisen", value: "eisen" },
        { label: "Hufschuhe", value: "hufschuhe" },
        { label: "Kunststoffbeschlag", value: "kunststoff" },
      ]},
      { id: uid(), type: "number", label: "Letzter Beschlag/Bearbeitung vor (Wochen)" },
      { id: uid(), type: "textarea", label: "Bekannte Hufprobleme", placeholder: "z.B. Hufrehe, Strahlfäule, Zwanghufe..." },
      { id: uid(), type: "textarea", label: "Sonstige Gesundheitshinweise", placeholder: "z.B. Medikamente, Allergien, TA-Kontakt..." },
      { id: uid(), type: "image", label: "Foto des Pferdes" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "signature", label: "Unterschrift Besitzer:in" },
    ],
  },
  {
    name: "Verlaufsdokumentation",
    description: "Fortlaufende Dokumentation über mehrere Termine",
    category: "verlauf",
    blocks: [
      { id: uid(), type: "heading", value: "Verlaufsdokumentation", headingLevel: 1 },
      { id: uid(), type: "placeholder", placeholderKey: "horse_name", label: "Pferd" },
      { id: uid(), type: "placeholder", placeholderKey: "client_name", label: "Besitzer:in" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "heading", value: "Termin", headingLevel: 2 },
      { id: uid(), type: "placeholder", placeholderKey: "date", label: "Datum" },
      { id: uid(), type: "number", label: "Termin Nr." },
      { id: uid(), type: "textarea", label: "Befund", placeholder: "Aktueller Zustand..." },
      { id: uid(), type: "textarea", label: "Maßnahmen", placeholder: "Was wurde gemacht..." },
      { id: uid(), type: "textarea", label: "Empfehlung / Nächste Schritte", placeholder: "Bearbeitungsintervall, Hufschutz-Empfehlung..." },
      { id: uid(), type: "image", label: "Foto" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "signature", label: "Unterschrift" },
    ],
  },
  {
    name: "Kundeninformation / Empfehlung",
    description: "Schriftliche Info oder Empfehlung für Kund:innen",
    category: "info",
    blocks: [
      { id: uid(), type: "heading", value: "Information & Empfehlung", headingLevel: 1 },
      { id: uid(), type: "placeholder", placeholderKey: "date", label: "Datum" },
      { id: uid(), type: "placeholder", placeholderKey: "client_name", label: "An" },
      { id: uid(), type: "placeholder", placeholderKey: "horse_name", label: "Betreff: Pferd" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "textarea", label: "Inhalt", placeholder: "Ihre Empfehlung oder Information...", rows: 8 },
      { id: uid(), type: "separator" },
      { id: uid(), type: "placeholder", placeholderKey: "provider_name", label: "Mit freundlichen Grüßen" },
    ],
  },
  {
    name: "Übergabeprotokoll",
    description: "Übergabe an neue:n Hufbearbeiter:in oder Tierarzt",
    category: "uebergabe",
    blocks: [
      { id: uid(), type: "heading", value: "Übergabeprotokoll", headingLevel: 1 },
      { id: uid(), type: "placeholder", placeholderKey: "date", label: "Datum" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "heading", value: "Pferd", headingLevel: 2 },
      { id: uid(), type: "placeholder", placeholderKey: "horse_name", label: "Name" },
      { id: uid(), type: "input", label: "Rasse / Alter" },
      { id: uid(), type: "heading", value: "Bisherige Betreuung", headingLevel: 2 },
      { id: uid(), type: "placeholder", placeholderKey: "provider_name", label: "Übergeben von" },
      { id: uid(), type: "input", label: "Übernommen von" },
      { id: uid(), type: "textarea", label: "Bearbeitungshistorie", placeholder: "Zusammenfassung bisheriger Behandlungen..." },
      { id: uid(), type: "textarea", label: "Aktuelle Hufsituation", placeholder: "Zustand, Besonderheiten, laufende Maßnahmen..." },
      { id: uid(), type: "textarea", label: "Empfehlungen für weiterführende Betreuung" },
      { id: uid(), type: "image", label: "Aktuelles Huf-Foto" },
      { id: uid(), type: "separator" },
      { id: uid(), type: "signature", label: "Unterschrift Übergeber:in" },
      { id: uid(), type: "signature", label: "Unterschrift Übernehmer:in" },
    ],
  },
];
