import { CanvasTemplate, CanvasBlock } from "./types";

function uid(): string {
  return crypto.randomUUID();
}

// Helper to create blocks with position
function b(type: CanvasBlock["type"], x: number, y: number, w: number, h: number, extra?: Partial<CanvasBlock>): CanvasBlock {
  return { id: uid(), type, x, y, width: w, height: h, ...extra };
}

export const FARRIER_TEMPLATES: CanvasTemplate[] = [
  {
    id: "tpl-hufbearbeitung",
    name: "Hufbearbeitungsprotokoll",
    description: "Standarddokumentation einer Hufbearbeitung mit Befund und Maßnahmen",
    category: "protokoll",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum", label: "Datum" }),
      b("auto-info", 400, 15, 175, 40, { autoInfoType: "betrieb", label: "Betrieb" }),
      b("text", 20, 65, 555, 45, { label: "Pferdename", placeholder: "Name des Pferdes" }),
      b("text", 20, 120, 270, 45, { label: "Besitzer:in", placeholder: "Name" }),
      b("text", 305, 120, 270, 45, { label: "Bearbeiter:in", placeholder: "Name" }),
      b("checkbox", 20, 180, 270, 140, {
        label: "Hufzustand vor Bearbeitung",
        checkboxItems: [
          { id: uid(), label: "Hufwand intakt", checked: false },
          { id: uid(), label: "Sohle gesund", checked: false },
          { id: uid(), label: "Strahl gesund", checked: false },
          { id: uid(), label: "Trachten gleichmäßig", checked: false },
        ],
      }),
      b("checkbox", 305, 180, 270, 140, {
        label: "Durchgeführte Maßnahmen",
        checkboxItems: [
          { id: uid(), label: "Ausschneiden", checked: false },
          { id: uid(), label: "Raspeln", checked: false },
          { id: uid(), label: "Sohle bearbeitet", checked: false },
          { id: uid(), label: "Hufschutz angebracht", checked: false },
        ],
      }),
      b("textarea", 20, 335, 555, 100, { label: "Besonderheiten / Auffälligkeiten", placeholder: "Beschreibung..." }),
      b("dropdown", 20, 450, 270, 60, {
        label: "Gangbild nach Bearbeitung",
        options: [
          { label: "Unauffällig", value: "unauffaellig" },
          { label: "Leichte Unregelmäßigkeit", value: "leicht" },
          { label: "Deutliche Unregelmäßigkeit", value: "deutlich" },
        ],
      }),
      b("image", 305, 450, 270, 170, { label: "Foto nach Bearbeitung" }),
      b("textarea", 20, 525, 270, 95, { label: "Empfehlungen", placeholder: "Nächste Schritte..." }),
      b("signature", 20, 640, 350, 160, { label: "Unterschrift Besitzer:in" }),
    ],
  },
  {
    id: "tpl-hufrehe",
    name: "Hufrehe-Dokumentation",
    description: "Spezialprotokoll für Hufrehe-Fälle mit Verlaufstracking",
    category: "protokoll",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum", label: "Datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd", placeholder: "Name, Rasse, Alter" }),
      b("text", 20, 65, 270, 45, { label: "Besitzer:in" }),
      b("text", 305, 65, 270, 45, { label: "Tierarzt" }),
      b("dropdown", 20, 125, 270, 60, {
        label: "Rehe-Stadium",
        options: [
          { label: "Akut", value: "akut" },
          { label: "Subakut", value: "subakut" },
          { label: "Chronisch", value: "chronisch" },
        ],
      }),
      b("scale", 305, 125, 270, 60, { label: "Schmerzgrad (1–10)", scaleMin: 1, scaleMax: 10 }),
      b("graphic", 20, 200, 270, 250, { label: "Hufbefund markieren", graphicType: "hoof-bottom" }),
      b("textarea", 305, 200, 270, 250, { label: "Detaillierter Befund", placeholder: "Rotation, Senkung, Sohlenzustand..." }),
      b("checkbox", 20, 465, 555, 100, {
        label: "Maßnahmen",
        checkboxItems: [
          { id: uid(), label: "Weichbettung", checked: false },
          { id: uid(), label: "Kühlung", checked: false },
          { id: uid(), label: "Hufschutz angepasst", checked: false },
          { id: uid(), label: "TA-Rücksprache", checked: false },
        ],
      }),
      b("textarea", 20, 580, 555, 80, { label: "Nächste Schritte / TA-Empfehlung" }),
      b("signature", 20, 680, 300, 140, { label: "Unterschrift" }),
    ],
  },
  {
    id: "tpl-erstbefund",
    name: "Erstbefund",
    description: "Erstanamnese eines neuen Pferdes mit vollständiger Datenerfassung",
    category: "aufnahme",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 20, 65, 270, 45, { label: "Pferdename", placeholder: "Name" }),
      b("text", 305, 65, 270, 45, { label: "Rasse" }),
      b("text", 20, 120, 170, 45, { label: "Alter" }),
      b("dropdown", 200, 120, 170, 60, {
        label: "Geschlecht",
        options: [
          { label: "Stute", value: "stute" },
          { label: "Wallach", value: "wallach" },
          { label: "Hengst", value: "hengst" },
        ],
      }),
      b("text", 380, 120, 195, 45, { label: "Farbe" }),
      b("text", 20, 190, 270, 45, { label: "Besitzer:in" }),
      b("text", 305, 190, 270, 45, { label: "Stallort / Adresse" }),
      b("dropdown", 20, 250, 270, 60, {
        label: "Aktueller Hufschutz",
        options: [
          { label: "Barhuf", value: "barhuf" },
          { label: "Eisen", value: "eisen" },
          { label: "Hufschuhe", value: "hufschuhe" },
          { label: "Kunststoffbeschlag", value: "kunststoff" },
        ],
      }),
      b("text", 305, 250, 270, 45, { label: "Letzte Bearbeitung vor (Wochen)" }),
      b("textarea", 20, 325, 555, 100, { label: "Bekannte Hufprobleme", placeholder: "Hufrehe, Strahlfäule, Zwanghufe..." }),
      b("graphic", 20, 440, 270, 220, { label: "Huf-Status", graphicType: "hooves-all" }),
      b("image", 305, 440, 270, 220, { label: "Foto des Pferdes" }),
      b("signature", 20, 680, 300, 140, { label: "Unterschrift Besitzer:in" }),
    ],
  },
  {
    id: "tpl-verlauf",
    name: "Verlaufskontrolle",
    description: "Fortlaufende Dokumentation über mehrere Termine",
    category: "verlauf",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 195, 40, { label: "Pferd" }),
      b("text", 405, 15, 170, 40, { label: "Termin Nr." }),
      b("text", 20, 65, 270, 45, { label: "Besitzer:in" }),
      b("auto-info", 305, 65, 270, 45, { autoInfoType: "betrieb" }),
      b("textarea", 20, 125, 555, 120, { label: "Aktueller Befund", placeholder: "Zustand seit letztem Termin..." }),
      b("graphic", 20, 260, 270, 220, { graphicType: "hooves-all", label: "Huf-Status markieren" }),
      b("textarea", 305, 260, 270, 220, { label: "Durchgeführte Maßnahmen" }),
      b("scale", 20, 495, 270, 60, { label: "Gesamtzustand (1–5)", scaleMin: 1, scaleMax: 5 }),
      b("textarea", 305, 495, 270, 80, { label: "Empfehlung / Nächste Schritte" }),
      b("image", 20, 580, 270, 120, { label: "Foto" }),
      b("signature", 305, 600, 270, 100, { label: "Unterschrift" }),
    ],
  },
  {
    id: "tpl-beschlag",
    name: "Beschlagprotokoll",
    description: "Detailliertes Beschlagprotokoll mit Materialien und Maßen",
    category: "protokoll",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd" }),
      b("text", 20, 65, 270, 45, { label: "Besitzer:in" }),
      b("auto-info", 305, 65, 270, 45, { autoInfoType: "betrieb" }),
      b("graphic", 20, 125, 200, 200, { graphicType: "hooves-all", label: "Beschlag-Übersicht" }),
      b("textarea", 230, 125, 345, 60, { label: "VL - Vorne Links", placeholder: "Typ, Größe, Bemerkung" }),
      b("textarea", 230, 195, 345, 60, { label: "VR - Vorne Rechts", placeholder: "Typ, Größe, Bemerkung" }),
      b("textarea", 230, 265, 345, 60, { label: "HL - Hinten Links", placeholder: "Typ, Größe, Bemerkung" }),
      b("textarea", 20, 340, 270, 60, { label: "HR - Hinten Rechts", placeholder: "Typ, Größe, Bemerkung" }),
      b("textarea", 305, 340, 270, 100, { label: "Verwendete Materialien", placeholder: "Eisen, Nägel, Polster..." }),
      b("textarea", 20, 415, 270, 100, { label: "Besonderheiten / Korrekturen" }),
      b("text", 20, 530, 270, 45, { label: "Nächster Termin in Wochen" }),
      b("image", 305, 455, 270, 180, { label: "Foto nach Beschlag" }),
      b("signature", 20, 680, 300, 140, { label: "Unterschrift Besitzer:in" }),
    ],
  },
  {
    id: "tpl-hufgeschwuer",
    name: "Befundbericht Hufgeschwür",
    description: "Dokumentation eines Hufgeschwürs mit Lokalisation und Behandlung",
    category: "protokoll",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd" }),
      b("text", 20, 65, 270, 45, { label: "Besitzer:in" }),
      b("dropdown", 305, 65, 270, 60, {
        label: "Betroffener Huf",
        options: [
          { label: "Vorne Links", value: "vl" },
          { label: "Vorne Rechts", value: "vr" },
          { label: "Hinten Links", value: "hl" },
          { label: "Hinten Rechts", value: "hr" },
        ],
      }),
      b("graphic", 20, 140, 270, 250, { graphicType: "hoof-bottom", label: "Lokalisation markieren" }),
      b("textarea", 305, 140, 270, 120, { label: "Befund", placeholder: "Größe, Tiefe, Eiter..." }),
      b("checkbox", 305, 270, 270, 120, {
        label: "Maßnahmen",
        checkboxItems: [
          { id: uid(), label: "Freigeschnitten", checked: false },
          { id: uid(), label: "Verband angelegt", checked: false },
          { id: uid(), label: "Desinfektion", checked: false },
          { id: uid(), label: "TA informiert", checked: false },
        ],
      }),
      b("textarea", 20, 405, 555, 80, { label: "Empfehlung / Nachbehandlung" }),
      b("image", 20, 500, 270, 170, { label: "Foto" }),
      b("signature", 305, 560, 270, 120, { label: "Unterschrift" }),
    ],
  },
  {
    id: "tpl-stellung",
    name: "Stellungsanalyse",
    description: "Gliedmaßen- und Hufform-Beurteilung mit Grafiken",
    category: "analyse",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd" }),
      b("graphic", 20, 70, 270, 250, { graphicType: "horse-side", label: "Seitenansicht markieren" }),
      b("graphic", 305, 70, 270, 250, { graphicType: "horse-leg", label: "Beinstellung markieren" }),
      b("scale", 20, 335, 270, 60, { label: "Zehe-Trachten-Verhältnis", scaleMin: 1, scaleMax: 5 }),
      b("scale", 305, 335, 270, 60, { label: "Symmetrie", scaleMin: 1, scaleMax: 5 }),
      b("graphic", 20, 410, 270, 220, { graphicType: "hooves-all", label: "Hufform alle 4" }),
      b("textarea", 305, 410, 270, 220, { label: "Beurteilung & Empfehlung", placeholder: "Stellungsanalyse-Ergebnis..." }),
      b("signature", 20, 650, 300, 160, { label: "Unterschrift Bearbeiter:in" }),
    ],
  },
  {
    id: "tpl-reha",
    name: "Reha-Protokoll",
    description: "Rehabilitationsprotokoll für Pferde nach Verletzung oder OP",
    category: "verlauf",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd" }),
      b("text", 20, 65, 270, 45, { label: "Diagnose / OP" }),
      b("text", 305, 65, 270, 45, { label: "Behandelnder TA" }),
      b("text", 20, 120, 170, 45, { label: "Reha-Woche" }),
      b("scale", 200, 120, 375, 60, { label: "Schmerzgrad (1–10)", scaleMin: 1, scaleMax: 10 }),
      b("checkbox", 20, 195, 270, 140, {
        label: "Heutige Maßnahmen",
        checkboxItems: [
          { id: uid(), label: "Hufbearbeitung", checked: false },
          { id: uid(), label: "Verband gewechselt", checked: false },
          { id: uid(), label: "Bewegungstherapie", checked: false },
          { id: uid(), label: "Hufschutz angepasst", checked: false },
        ],
      }),
      b("textarea", 305, 195, 270, 140, { label: "Fortschritt seit letztem Termin" }),
      b("graphic", 20, 350, 270, 220, { graphicType: "hoof-side", label: "Hufzustand" }),
      b("textarea", 305, 350, 270, 100, { label: "TA-Empfehlung" }),
      b("textarea", 305, 465, 270, 105, { label: "Nächste Schritte" }),
      b("image", 20, 585, 270, 120, { label: "Foto" }),
      b("signature", 305, 600, 270, 120, { label: "Unterschrift" }),
    ],
  },
  {
    id: "tpl-uebergabe",
    name: "Kundenübergabe",
    description: "Übergabeprotokoll an neue:n Hufbearbeiter:in oder Tierarzt",
    category: "uebergabe",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd" }),
      b("text", 20, 65, 270, 45, { label: "Übergeben von" }),
      b("text", 305, 65, 270, 45, { label: "Übernommen von" }),
      b("text", 20, 120, 270, 45, { label: "Besitzer:in" }),
      b("text", 305, 120, 270, 45, { label: "Rasse / Alter" }),
      b("textarea", 20, 180, 555, 120, { label: "Bearbeitungshistorie", placeholder: "Zusammenfassung bisheriger Behandlungen..." }),
      b("textarea", 20, 315, 555, 120, { label: "Aktuelle Hufsituation", placeholder: "Zustand, Besonderheiten, laufende Maßnahmen..." }),
      b("graphic", 20, 450, 270, 200, { graphicType: "hooves-all", label: "Aktueller Hufstatus" }),
      b("textarea", 305, 450, 270, 100, { label: "Empfehlungen für Weiterbetreuung" }),
      b("image", 305, 560, 270, 90, { label: "Aktuelles Huf-Foto" }),
      b("signature", 20, 670, 270, 140, { label: "Übergeber:in" }),
      b("signature", 305, 670, 270, 140, { label: "Übernehmer:in" }),
    ],
  },
  {
    id: "tpl-jahresbericht",
    name: "Jahresbericht",
    description: "Jährliche Zusammenfassung des Hufzustands eines Pferdes",
    category: "analyse",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd" }),
      b("text", 20, 65, 270, 45, { label: "Besitzer:in" }),
      b("auto-info", 305, 65, 270, 45, { autoInfoType: "betrieb" }),
      b("text", 20, 120, 270, 45, { label: "Berichtszeitraum" }),
      b("text", 305, 120, 270, 45, { label: "Anzahl Termine" }),
      b("textarea", 20, 180, 555, 120, { label: "Zusammenfassung des Jahres", placeholder: "Entwicklung, Fortschritte, Probleme..." }),
      b("scale", 20, 315, 270, 60, { label: "Hufzustand Jahresbeginn", scaleMin: 1, scaleMax: 5 }),
      b("scale", 305, 315, 270, 60, { label: "Hufzustand Jahresende", scaleMin: 1, scaleMax: 5 }),
      b("graphic", 20, 390, 270, 220, { graphicType: "hooves-all", label: "Aktueller Status" }),
      b("textarea", 305, 390, 270, 120, { label: "Empfehlungen für kommendes Jahr" }),
      b("image", 305, 520, 270, 90, { label: "Vergleichsfoto" }),
      b("textarea", 20, 625, 555, 60, { label: "Sonstige Hinweise" }),
      b("signature", 20, 700, 300, 120, { label: "Unterschrift Bearbeiter:in" }),
    ],
  },
  // ── Kommunikation ──────────────────────
  {
    id: "tpl-ta-empfehlung",
    name: "Behandlungsempfehlung an Tierarzt",
    description: "Offizielles Schreiben mit Befund und Empfehlung an den Tierarzt",
    category: "kommunikation",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("auto-info", 400, 15, 175, 40, { autoInfoType: "betrieb" }),
      b("text", 20, 65, 555, 45, { label: "An: Tierarztpraxis", placeholder: "Name der Praxis" }),
      b("text", 20, 120, 270, 45, { label: "Betreff: Pferd", placeholder: "Name, Rasse, Alter" }),
      b("text", 305, 120, 270, 45, { label: "Besitzer:in" }),
      b("textarea", 20, 180, 555, 120, { label: "Hufbefund", placeholder: "Beschreibung des aktuellen Hufzustands..." }),
      b("textarea", 20, 315, 555, 120, { label: "Empfehlung / Rückfrage", placeholder: "Empfohlene Maßnahmen, Rücksprache gewünscht zu..." }),
      b("graphic", 20, 450, 270, 200, { graphicType: "hooves-all", label: "Hufstatus markieren" }),
      b("image", 305, 450, 270, 200, { label: "Foto zur Dokumentation" }),
      b("signature", 20, 670, 300, 140, { label: "Unterschrift Hufbearbeiter:in" }),
    ],
  },
  {
    id: "tpl-hufschuh-empfehlung",
    name: "Empfehlung Hufschuhe",
    description: "Produktempfehlung für Hufschuhe mit fachlicher Begründung",
    category: "kommunikation",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 20, 65, 270, 45, { label: "Pferd" }),
      b("text", 305, 65, 270, 45, { label: "Besitzer:in" }),
      b("textarea", 20, 125, 555, 100, { label: "Begründung", placeholder: "Warum Hufschuhe empfohlen werden..." }),
      b("text", 20, 240, 270, 45, { label: "Empfohlenes Modell" }),
      b("text", 305, 240, 270, 45, { label: "Größe" }),
      b("textarea", 20, 300, 555, 100, { label: "Hinweise zur Nutzung", placeholder: "Einlaufzeit, Pflege, Einsatzbereich..." }),
      b("graphic", 20, 415, 270, 200, { graphicType: "hooves-all", label: "Hufmaße" }),
      b("image", 305, 415, 270, 200, { label: "Foto" }),
      b("signature", 20, 640, 300, 160, { label: "Unterschrift" }),
    ],
  },
  // ── Verwaltung ──────────────────────────
  {
    id: "tpl-dsgvo",
    name: "Datenschutzerklärung Kundenaufnahme",
    description: "DSGVO-konforme Einwilligungserklärung für neue Kunden",
    category: "verwaltung",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("auto-info", 400, 15, 175, 40, { autoInfoType: "betrieb" }),
      b("text", 20, 65, 270, 45, { label: "Name des Kunden" }),
      b("text", 305, 65, 270, 45, { label: "Adresse" }),
      b("textarea", 20, 125, 555, 200, {
        label: "Datenschutzhinweis",
        value: "Ich willige ein, dass meine personenbezogenen Daten (Name, Kontaktdaten, Pferdedaten) zum Zweck der Hufbearbeitung und Terminplanung gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben, es sei denn, dies ist zur Erfüllung des Auftrags erforderlich (z.B. Tierarzt-Kommunikation). Ich kann diese Einwilligung jederzeit widerrufen.",
      }),
      b("checkbox", 20, 340, 555, 120, {
        label: "Einwilligungen",
        checkboxItems: [
          { id: uid(), label: "Ich habe die Datenschutzerklärung gelesen und stimme zu", checked: false },
          { id: uid(), label: "Fotos dürfen zu Dokumentationszwecken erstellt werden", checked: false },
          { id: uid(), label: "Kontaktaufnahme per WhatsApp/E-Mail ist erlaubt", checked: false },
        ],
      }),
      b("signature", 20, 480, 270, 160, { label: "Unterschrift Kunde" }),
      b("auto-info", 305, 480, 270, 40, { autoInfoType: "zeitstempel", label: "Zeitstempel" }),
    ],
  },
  {
    id: "tpl-preisliste",
    name: "Preisliste",
    description: "Strukturierte Preisliste für Kunden als PDF",
    category: "verwaltung",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "betrieb" }),
      b("auto-info", 400, 15, 175, 40, { autoInfoType: "datum", label: "Stand" }),
      b("text", 20, 65, 555, 50, { label: "Preisliste", fontSize: 20 }),
      b("textarea", 20, 130, 555, 300, {
        label: "Leistungen & Preise",
        placeholder: "Hufbearbeitung (Barhuf) .............. ab 35 €\nHufbearbeitung (Beschlag) ............. ab 85 €\nErstbefund / Anamnese ................. ab 45 €\nNotfall-Zuschlag ...................... + 20 €\nAnfahrt (ab 30 km) ................... 0,45 €/km",
      }),
      b("textarea", 20, 445, 555, 100, { label: "Hinweise", placeholder: "Alle Preise verstehen sich inkl./zzgl. MwSt. Abweichungen nach Aufwand möglich." }),
      b("text", 20, 560, 555, 45, { label: "Kontakt", placeholder: "Tel. / E-Mail / Website" }),
    ],
  },
  {
    id: "tpl-angebot",
    name: "Angebot",
    description: "Individuelles Angebot für Kunden mit Leistungsbeschreibung",
    category: "verwaltung",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("auto-info", 400, 15, 175, 40, { autoInfoType: "betrieb" }),
      b("text", 20, 65, 555, 45, { label: "Angebot für", placeholder: "Name des Kunden / Stallname" }),
      b("text", 20, 120, 270, 45, { label: "Pferd(e)", placeholder: "Name(n)" }),
      b("text", 305, 120, 270, 45, { label: "Angebots-Nr." }),
      b("textarea", 20, 180, 555, 200, { label: "Leistungsbeschreibung", placeholder: "Beschreibung der angebotenen Leistungen..." }),
      b("text", 20, 395, 270, 45, { label: "Gesamtpreis (netto)" }),
      b("text", 305, 395, 270, 45, { label: "Gültig bis" }),
      b("textarea", 20, 455, 555, 80, { label: "Bedingungen", placeholder: "Zahlungsbedingungen, Anfahrt, Sonstiges..." }),
      b("signature", 20, 550, 270, 140, { label: "Unterschrift Anbieter" }),
      b("signature", 305, 550, 270, 140, { label: "Unterschrift Kunde (Annahme)" }),
    ],
  },
  // ── Notfall ──────────────────────────────
  {
    id: "tpl-notfallprotokoll",
    name: "Notfallprotokoll",
    description: "Schnelldokumentation bei Notfall mit vereinfachtem Layout",
    category: "notfall",
    blocks: [
      b("auto-info", 20, 15, 200, 40, { autoInfoType: "zeitstempel", label: "Zeitstempel" }),
      b("text", 230, 15, 345, 40, { label: "⚠️ NOTFALL – Pferd" }),
      b("text", 20, 65, 270, 45, { label: "Besitzer:in / Kontakt" }),
      b("text", 305, 65, 270, 45, { label: "Tierarzt informiert?" }),
      b("dropdown", 20, 125, 270, 60, {
        label: "Art des Notfalls",
        options: [
          { label: "Hufgeschwür akut", value: "abscess" },
          { label: "Nageltritt", value: "nail" },
          { label: "Hufrehe akut", value: "laminitis" },
          { label: "Verletzung am Huf", value: "injury" },
          { label: "Eisen verloren", value: "shoe_lost" },
          { label: "Sonstiges", value: "other" },
        ],
      }),
      b("scale", 305, 125, 270, 60, { label: "Schmerzgrad (1–10)", scaleMin: 1, scaleMax: 10 }),
      b("textarea", 20, 200, 555, 120, { label: "Sofortbefund", placeholder: "Was wurde festgestellt?" }),
      b("checkbox", 20, 335, 555, 120, {
        label: "Sofortmaßnahmen",
        checkboxItems: [
          { id: uid(), label: "Kühlung", checked: false },
          { id: uid(), label: "Verband angelegt", checked: false },
          { id: uid(), label: "Hufschutz entfernt/angepasst", checked: false },
          { id: uid(), label: "Weichbettung", checked: false },
          { id: uid(), label: "TA gerufen", checked: false },
        ],
      }),
      b("image", 20, 470, 270, 170, { label: "Foto" }),
      b("textarea", 305, 470, 270, 170, { label: "Nächste Schritte / TA-Anweisung" }),
      b("signature", 20, 660, 300, 140, { label: "Unterschrift" }),
    ],
  },
  {
    id: "tpl-kolik-bogen",
    name: "Kolik-Beobachtungsbogen",
    description: "Stündliche Verlaufsdokumentation für Kolik-Verdacht",
    category: "notfall",
    blocks: [
      b("auto-info", 20, 15, 150, 40, { autoInfoType: "datum" }),
      b("text", 200, 15, 375, 40, { label: "Pferd" }),
      b("text", 20, 65, 270, 45, { label: "Besitzer:in" }),
      b("text", 305, 65, 270, 45, { label: "Tierarzt" }),
      b("text", 20, 120, 170, 45, { label: "Uhrzeit Beginn" }),
      b("scale", 200, 120, 375, 60, { label: "Schmerzgrad aktuell (1–10)", scaleMin: 1, scaleMax: 10 }),
      b("checkbox", 20, 195, 270, 180, {
        label: "Symptome",
        checkboxItems: [
          { id: uid(), label: "Flehmen / Zum Bauch schauen", checked: false },
          { id: uid(), label: "Scharren / Wälzen", checked: false },
          { id: uid(), label: "Schwitzen", checked: false },
          { id: uid(), label: "Kein Kotabsatz", checked: false },
          { id: uid(), label: "Keine Darmgeräusche", checked: false },
          { id: uid(), label: "Futteraufnahme verweigert", checked: false },
        ],
      }),
      b("textarea", 305, 195, 270, 180, { label: "Beobachtungen (stündlich)", placeholder: "Uhrzeit – Zustand – Maßnahmen..." }),
      b("textarea", 20, 390, 555, 100, { label: "Tierärztliche Anweisungen" }),
      b("textarea", 20, 505, 555, 80, { label: "Verlauf / Entwarnung" }),
      b("signature", 20, 600, 270, 120, { label: "Beobachter:in" }),
      b("auto-info", 305, 600, 270, 40, { autoInfoType: "zeitstempel", label: "Letzter Eintrag" }),
    ],
  },
];
