// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-horses.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Nicht authentifiziert. Bitte die Verbindung neu autorisieren." }],
    isError: true
  };
}
function toolError(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
function jsonResult(data) {
  return {
    content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
    structuredContent: { data }
  };
}

// src/lib/mcp/tools/list-horses.ts
var list_horses_default = defineTool({
  name: "list_horses",
  title: "Pferde auflisten",
  description: "Listet die Pferde auf, auf die der angemeldete Nutzer Zugriff hat. Optional nach Name oder EQID gefiltert.",
  inputSchema: {
    search: z.string().optional().describe("Optionaler Suchbegriff (Pferdename oder EQID)."),
    limit: z.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("horses").select("id, eqid, name, nickname, breed, birth_year, gender, color, hoof_type, shoeing_interval, location_name, next_appointment_due, last_appointment_date").is("deleted_at", null).order("name").limit(max);
    if (search?.trim()) {
      const term = search.trim();
      query = query.or(`name.ilike.%${term}%,eqid.ilike.%${term}%,nickname.ilike.%${term}%`);
    }
    const { data, error } = await query;
    if (error) return toolError(error.message);
    return jsonResult({ count: data?.length ?? 0, horses: data ?? [] });
  }
});

// src/lib/mcp/tools/get-horse.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_horse_default = defineTool2({
  name: "get_horse",
  title: "Pferdedetails abrufen",
  description: "Liefert das vollst\xE4ndige Pferdeprofil (Stammdaten, Huf-Infos, Gesundheit) anhand der Pferde-ID oder EQID.",
  inputSchema: {
    horse_id: z2.string().optional().describe("UUID des Pferdes."),
    eqid: z2.string().optional().describe("Lesbare EQID des Pferdes, falls die UUID unbekannt ist.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ horse_id, eqid }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    if (!horse_id && !eqid) return toolError("Bitte horse_id oder eqid angeben.");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("horses").select(
      "id, eqid, name, nickname, official_name, breed, birth_year, birth_date, gender, color, height_cm, discipline, usage_type, housing, hoof_type, hoof_protection, shoeing_interval, recall_interval_weeks, health_status, health_issues_general, known_allergies, current_medications, special_notes, location_name, last_appointment_date, next_appointment_due"
    ).is("deleted_at", null).limit(1);
    query = horse_id ? query.eq("id", horse_id) : query.eq("eqid", eqid);
    const { data, error } = await query.maybeSingle();
    if (error) return toolError(error.message);
    if (!data) return toolError("Pferd nicht gefunden oder kein Zugriff.");
    return jsonResult(data);
  }
});

// src/lib/mcp/tools/list-appointments.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_appointments_default = defineTool3({
  name: "list_appointments",
  title: "Termine auflisten",
  description: "Listet Termine des angemeldeten Nutzers in einem Datumsbereich (Standard: ab heute).",
  inputSchema: {
    from: z3.string().optional().describe("Startdatum im Format YYYY-MM-DD. Standard: heute."),
    to: z3.string().optional().describe("Enddatum im Format YYYY-MM-DD."),
    status: z3.string().optional().describe("Optionaler Status-Filter, z. B. scheduled oder completed."),
    limit: z3.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    const start = from?.trim() || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let query = supabase.from("appointments").select("id, date, time, duration, service_type, status, location, notes, price, horse_id, horses(name, eqid)").gte("date", start).order("date").order("time").limit(max);
    if (to?.trim()) query = query.lte("date", to.trim());
    if (status?.trim()) query = query.eq("status", status.trim());
    const { data, error } = await query;
    if (error) return toolError(error.message);
    return jsonResult({ count: data?.length ?? 0, from: start, appointments: data ?? [] });
  }
});

// src/lib/mcp/tools/list-invoices.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var list_invoices_default = defineTool4({
  name: "list_invoices",
  title: "Rechnungen auflisten",
  description: "Listet Rechnungen des angemeldeten Nutzers, optional nach Status gefiltert.",
  inputSchema: {
    status: z4.string().optional().describe("Status-Filter, z. B. sent, paid oder overdue."),
    limit: z4.number().int().optional().describe("Maximale Anzahl Ergebnisse (Standard 25, max 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const max = Math.min(Math.max(limit ?? 25, 1), 100);
    let query = supabase.from("invoices").select("id, invoice_number, issue_date, due_date, total_amount, status, payment_status, paid_at, horse_id").order("issue_date", { ascending: false }).limit(max);
    if (status?.trim()) query = query.eq("status", status.trim());
    const { data, error } = await query;
    if (error) return toolError(error.message);
    const open = (data ?? []).filter((i) => i.status !== "paid");
    return jsonResult({
      count: data?.length ?? 0,
      open_amount: open.reduce((sum, i) => sum + Number(i.total_amount ?? 0), 0),
      invoices: data ?? []
    });
  }
});

// src/lib/mcp/index.ts
var projectRef = "vnschgjxkzzwzefqlrji";
var mcp_default = defineMcp({
  name: "hufmanager",
  title: "HufManager",
  version: "0.1.0",
  instructions: "Tools f\xFCr HufManager, die Management-App f\xFCr mobile Pferdeprofis. Zugriff erfolgt als angemeldeter Nutzer: Pferde suchen und Details abrufen (list_horses, get_horse), Termine im Kalender einsehen (list_appointments) und Rechnungsstatus pr\xFCfen (list_invoices).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_horses_default, get_horse_default, list_appointments_default, list_invoices_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
