-- Micro-Hardening zwischen Migration #5 (20260917150000) und #6 (20260917155000).
--
-- ── Befund ──────────────────────────────────────────────────────────────────
-- Der Supabase Security Advisor meldet nach #5 neu:
--
--   function_search_path_mutable  ->  public._hm_normalize_email(text)
--
-- #5 hat auf ihren fuenf SECURITY-DEFINER-Funktionen konsequent
-- SET search_path = public gesetzt, auf diesem einen SECURITY-INVOKER-Helper
-- aber nicht. Damit ist _hm_normalize_email die einzige von 195 Routinen in
-- public ohne festen search_path — die einzige Abweichung von einer sonst
-- vollstaendig durchgehaltenen Projektkonvention.
--
-- ── Ist der Befund echt? ────────────────────────────────────────────────────
-- Ja. Gegen eine isolierte Testinstanz gemessen (nicht Production):
--
--   search_path = public                 ->  korrekt normalisiert
--   search_path = evil, public           ->  korrekt normalisiert (unveraendert)
--   search_path = evil, pg_catalog, public -> shadowendes evil.lower() greift
--
-- pg_catalog wird implizit zuerst durchsucht, solange es nicht ausdruecklich
-- HINTER einem fremden Schema einsortiert wird. Genau dieser Sonderfall laesst
-- lower()/btrim() ueberschreiben. coalesce()/nullif() sind SQL-Konstrukte und
-- grundsaetzlich nicht shadowbar.
--
-- ── Warum er trotzdem nicht ausnutzbar war ──────────────────────────────────
-- Ein Angriff braucht drei Dinge gleichzeitig: ein eigenes Schema mit
-- shadowenden Funktionen, Kontrolle ueber search_path, und EXECUTE auf diese
-- Funktion. Read-only gegen Production geprueft:
--
--   anon / authenticated / authenticator : kein CREATE, kein EXECUTE
--   service_role                         : EXECUTE ja, CREATE nein
--   postgres                             : beides — kann die Funktion aber
--                                          ohnehin direkt umschreiben
--
-- Zudem ist die Funktion SECURITY INVOKER: selbst bei manipulierter Aufloesung
-- entstuende kein Rechtegewinn. Der Befund war deshalb in NACHTRAG 8 als
-- REAL_BUT_NOT_EXPLOITABLE_DOCUMENTED_RESIDUAL eingestuft und hat #5 nicht
-- blockiert. Er wird hier geschlossen, weil ein dauerhaft offener Restbefund
-- die Konvention aufweicht, an der spaetere Reviews sich orientieren.
--
-- ── Warum search_path = public und nicht pg_catalog, public ─────────────────
-- Sobald der search_path fest am Objekt haengt, kann ein Aufrufer ueberhaupt
-- kein fremdes Schema mehr davorschieben — der oben gezeigte Angriffspfad
-- existiert dann nicht mehr. pg_catalog bleibt implizit an erster Stelle.
-- 'public' ist damit ebenso sicher wie 'pg_catalog, public' und identisch zu
-- dem, was die fuenf SECURITY-DEFINER-Funktionen aus #5 und die uebrigen
-- Routinen dieses Projekts verwenden. Konsistenz schlaegt hier Sonderweg.
--
-- ── Warum ALTER FUNCTION und nicht CREATE OR REPLACE ────────────────────────
-- ALTER FUNCTION ... SET aendert ausschliesslich pg_proc.proconfig. Body
-- (prosrc), Sprache, Volatilitaet, Rueckgabetyp, Strictness, Owner und ACL
-- bleiben nachweislich unberuehrt — prosrc-md5 vor und nach der Migration ist
-- identisch. CREATE OR REPLACE wuerde den Body neu schreiben und diesen
-- Beweis unnoetig aufgeben.
--
-- Diese Migration ist idempotent: ein zweiter Lauf setzt denselben Wert.
--
-- ── Bewusst NICHT Teil dieser Migration ─────────────────────────────────────
--   * keine Body-/Semantikaenderung
--   * keine Grant-/ACL-Aenderung
--   * keine RLS-Aenderung — insbesondere bleibt
--     public.hm_pending_client_invites bei RLS ohne Policy: das ist der
--     beabsichtigte Default-Deny-Vertrag aus #5, kein Defekt
--   * keine Tabellen-, Index- oder Constraint-Aenderung
--   * keine Datenmutation
--   * keine Trigger- oder Policy-Aenderung
--   * nichts aus #6-#9, kein Edge-Function-Deploy, kein Vault-Zugriff

ALTER FUNCTION public._hm_normalize_email(text) SET search_path = public;
