// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { ACTIVE_FLAVOR } from '@/config/appFlavor';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// HufManager: Session nur fuer die aktuelle Browser-Sitzung behalten.
// Dadurch bleibt ein Reload waehrend der Arbeit moeglich, aber nach Schliessen
// des Tabs/Browsers wird beim naechsten Start wieder eine Anmeldung verlangt.
// HufiApp behaelt vorerst das bestehende persistente Verhalten.
const authStorage = ACTIVE_FLAVOR === 'hufmanager' ? sessionStorage : localStorage;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
